apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
data:
  AUTH_KEY:
  SECURE_AUTH_KEY:
  LOGGED_IN_KEY:
  NONCE_KEY:
  AUTH_SALT:
  SECURE_AUTH_SALT:
  LOGGED_IN_SALT:
  NONCE_SALT:
  DB_PASSWORD:
